function Hd = gen_iir_osix_bp(Fc1, Fc2, Fs)

% EDITED AUTOGEN FROM FILTER DESIGNER

%GEN_IIR_OSIX_BP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 18-Nov-2021 12:27:19

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.
N   = 6;      % Order

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]